export const AUTH_EXTRACT_TOKEN = "AUTH_EXTRACT_TOKEN";
export const AUTH_SET_TOKEN = "AUTH_SET_TOKEN";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
