export const USER_ACCOUNT_REQUEST = "USER_ACCOUNT_REQUEST";
export const USER_ACCOUNT_SUCCESS = "USER_ACCOUNT_SUCCESS";
export const USER_ACCOUNT_ERROR = "USER_ACCOUNT_ERROR";

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_ERROR = "USER_PROFILE_ERROR";
