## Google
spring.security.oauth2.client.registration.google.client-id: 279784554172-c9k33663rco8m2o5f1p43ej9ec42fit5.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret: 7UJBkyQL-cjGbq_lrB0nrkmm

## LinkedIn
spring.security.oauth2.client.registration.linkedIn.client-id: 86q0889a82ojla
spring.security.oauth2.client.registration.linkedIn.client-secret: 2bsyqKpxo4s9FGfz

## GitLab
spring.security.oauth2.client.registration.gitlab.client-id: 9dd22e4d231bb7282e0b7b4f51b4cf218b97275dc5c25b9abdd27d172c553234
spring.security.oauth2.client.registration.gitlab.client-secret: 9544b3685db57e0abcdb7b9dd6ca534fa999d8c4bbea843d13cb3206b4592278
